-- Create or update audit_logs table with correct schema
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  user_id TEXT,
  details JSONB,
  ip TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_ip ON audit_logs(ip);

ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;

-- View recent audit logs
SELECT 
  id,
  action,
  user_id,
  ip,
  created_at,
  details::text as details
FROM audit_logs
ORDER BY created_at DESC
LIMIT 50;
