-- Telegram Integration Table Migration
-- Run this script in your Supabase SQL Editor to add Telegram support

-- Create Telegram Chat Registrations Table
CREATE TABLE IF NOT EXISTS telegram_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id UUID NOT NULL UNIQUE REFERENCES faculty(id) ON DELETE CASCADE,
  telegram_chat_id BIGINT NOT NULL,
  telegram_username TEXT,
  registered_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT TRUE
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS telegram_chats_faculty_id_idx ON telegram_chats (faculty_id);
CREATE INDEX IF NOT EXISTS telegram_chats_chat_id_idx ON telegram_chats (telegram_chat_id);

ALTER TABLE telegram_chats DISABLE ROW LEVEL SECURITY;

-- Add telegram registration field to faculty table for tracking pending registrations
ALTER TABLE faculty ADD COLUMN IF NOT EXISTS telegram_registration_token TEXT UNIQUE;
ALTER TABLE faculty ADD COLUMN IF NOT EXISTS telegram_registration_expires_at TIMESTAMPTZ;

-- Telegram Notification Logs (optional, for audit/debugging)
CREATE TABLE IF NOT EXISTS telegram_notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id UUID NOT NULL REFERENCES faculty(id),
  queue_id UUID REFERENCES queue(id),
  message_type TEXT NOT NULL, -- 'status_update', 'notification', etc.
  message_text TEXT,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  telegram_message_id BIGINT,
  status TEXT DEFAULT 'sent', -- 'sent', 'failed', 'pending'
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS telegram_notification_logs_faculty_id_idx ON telegram_notification_logs (faculty_id);
CREATE INDEX IF NOT EXISTS telegram_notification_logs_sent_at_idx ON telegram_notification_logs (sent_at DESC);

ALTER TABLE telegram_notification_logs DISABLE ROW LEVEL SECURITY;
